apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: pm-digital-twin
build:
  artifacts:
    - image: predictivemovement/sample-address
      context: packages/sampleAddresses
    - image: predictivemovement/digital-twin-simulator
      context: packages/simulator
    - image: predictivemovement/digital-twin-visualisation
      context: packages/visualisation
      docker:
        buildArgs:
          VITE_MAPBOX_ACCESS_TOKEN: "{{.VITE_MAPBOX_ACCESS_TOKEN}}"
          VITE_SIMULATOR_URL: /
# manifests:
#   kustomize:
#     paths:
#       - k8s/base
# deploy:
#   statusCheckDeadlineSeconds: 600
#profiles:
#  - name: prod
#    activation:
#      - env: GITHUB_REF_TYPE=tag
#    manifests:
#      kustomize:
#        paths:
#          - k8s/overlays/helsingborg
#          - k8s/overlays/rorla
#          - k8s/overlays/digital-twin
