services:
  osrm-data:
    image: irony/osrm5
    volumes:
      - /data

  osrm:
    image: irony/osrm5 
    volumes_from: 
      - osrm-data
    ports:
      - 5000:5000
    command: ./start.sh Sweden http://download.geofabrik.de/europe/sweden-latest.osm.pbf
    
  # valhalla:
  #   image: aray12/valhalla-docker
  #   ports:
  #     - 8002:8002
