apiVersion: skaffold/v2alpha4
kind: Config
metadata:
  name: pm-digital-twin
deploy:
  kubectl:
    manifests:
      # - namespaces.yaml
      # - nginx.yaml
      # - cert-manager.yaml
      - cluster-issuer.yaml
      - cluster-crt.yaml
      - elasticsearch.yaml