apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: digital-twin

resources:
- ../../base/digital-twin

patches:
- path: visualisation.yaml
- path: simulator.yaml
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: REGIONS
        value: "*"
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: TRAFIKLAB_KEY
        value: "82a471015a8d426688de5174eb105d1f"
  target:
    kind: Deployment
    name: simulator

# Trafiklab API: https://developer.trafiklab.se/user/24158/keys
