apiVersion: skaffold/v2alpha4
kind: Config
metadata:
  name: pm-digital-twin
# build:
#   artifacts:
#     - image: predictivemovement/otp-sweden
#       context: opentripplanner
#       docker:
#         buildArgs:
#           apikey: "82a471015a8d426688de5174eb105d1f"
#           operator: norrbotten
#     - image: predictivemovement/osrm-sweden
#       context: osrm
#     - image: predictivemovement/sample-address
#       context: packages/sampleAddresses
deploy:
  kubectl:
    manifests:
      # - pelias/*.yaml
      - osrm/*.yaml
      - vroom/*.yaml
      - opentripplanner/*.yaml
#      - sampleAddresses/*.yaml
# portForward:
#   - resourceType: deployment
#     resourceName: kibana
#     port: 5601
#     localPort: 5601
#   - resourceType: deployment
#     resourceName: pelias-api
#     port: 4000
#     localPort: 4000
#  - resourceType: deployment
#    resourceName: osrm-backend
#    port: 5000
#    localPort: 5000
#  - resourceType: deployment
#    resourceName: vroom
#    port: 3000
#    localPort: 3001
#  - resourceType: deployment
#    resourceName: otp-sweden
#    port: 8080
#    localPort: 8080
